apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: amazonEBS
spec:
  storageClassName: gp2
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0f78228671fd52610
    fsType: ext4

    # vol-0f78228671fd52610