apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mysql-restore
          envFrom:
          - secretRef:
              name: sosialmedia-mysql-secret
          image: mysql:5.6
          command: [sh, -c]
          args: ["-c", "apt-get update -y && apt-get install wget -y && wget https://raw.githubusercontent.com/yusufluaii/kubernetes-sd/main/src/dump.sql && mysql -h mysql -p12345678 dbsosmed < dump.sql"]